function js(value: unknown): string { return JSON.stringify(value, null, 2); }
function ident(value: string): string { const s=value.replace(/[^A-Za-z0-9_$]+(.)?/g,(_m,c)=>c?String(c).toUpperCase():""); return /^\d/.test(s)?`_${s}`:(s||"operation"); }

export function operationCatalog(openapi: any) {
  const out: any[] = [];
  for (const [path,pathItem] of Object.entries<any>(openapi.paths ?? {})) {
    for (const [method,operation] of Object.entries<any>(pathItem ?? {})) {
      if (!operation?.operationId || !["get","post","put","patch","delete"].includes(method)) continue;
      out.push({
        operationId: operation.operationId, method: method.toUpperCase(), path,
        group: operation["x-powerfarm-group"] ?? operation.tags?.[0] ?? "default",
        name: operation["x-powerfarm-method"] ?? operation.operationId.split(".").at(-1),
        capability: operation["x-powerfarm-capability"] ?? null,
        hidden: Boolean(operation["x-powerfarm-hidden"]),
      });
    }
  }
  return out.sort((a,b)=>a.operationId.localeCompare(b.operationId));
}

export function generateSdk(openapi: any): string {
  const ops = operationCatalog(openapi).filter(o=>!o.hidden);
  const groups = new Map<string, any[]>();
  for (const op of ops) { const list=groups.get(op.group)??[]; list.push(op); groups.set(op.group,list); }
  const groupLines = [...groups.entries()].sort(([a],[b])=>a.localeCompare(b)).map(([group,items]) => {
    const methods=items.map(op=>`${js(ident(op.name))}: (input={}) => this.call(${js(op.operationId)}, input)`).join(",\n        ");
    return `${js(ident(group))}: {\n        ${methods}\n      }`;
  }).join(",\n      ");
  return `// Generated by Powerfarm contract compiler. Do not edit manually.\nconst operations = ${js(Object.fromEntries(ops.map(o=>[o.operationId,o])))};\n\nexport class PowerfarmClient {\n  constructor(options={}) {\n    this.baseUrl=(options.baseUrl ?? "http://127.0.0.1:4545").replace(/\\/$/, "");\n    this.token=options.token ?? "powerfarm-local-admin";\n    this.api = {\n      ${groupLines}\n    };\n  }\n  async call(operationId, input={}) {\n    const op=operations[operationId]; if(!op) throw new Error(\`Unknown operation: \${operationId}\`);\n    let path=op.path; const body={...input};\n    path=path.replace(/\\{([^}]+)\\}/g,(_m,key)=>{if(!(key in body)) throw new Error(\`Missing path parameter \${key}\`); const value=body[key]; delete body[key]; return encodeURIComponent(value)});\n    const init={method:op.method,headers:{authorization:\`Bearer \${this.token}\`}};\n    if(!["GET","HEAD"].includes(op.method)){init.headers["content-type"]="application/json";init.body=JSON.stringify(body)}\n    else { const q=new URLSearchParams(Object.entries(body).filter(([,v])=>v!==undefined&&v!==null).map(([k,v])=>[k,String(v)])); if([...q].length) path += \`?\${q}\`; }\n    const response=await fetch(this.baseUrl+path,init); const payload=await response.json(); if(!response.ok) throw new Error(payload?.error?.message ?? \`HTTP \${response.status}\`); return payload.data ?? payload;\n  }\n}\n\nexport { operations };\n`;
}
