import type { Database } from "../../db/src/database.ts";
import { toJson } from "../../core/src/json.ts";
import { nowIso } from "../../core/src/time.ts";

export interface ReplayAct {id:string;actor_id:string;kind:string;object_type:string;object_id:string;payload:any;evidence_digest?:string|null;created_at:string}

export function replayAct(db:Database,act:ReplayAct):void{
  const p=act.payload??{}; const t=act.created_at||nowIso();
  switch(act.kind){
    case "entity.recognized": db.run("INSERT OR IGNORE INTO entities(id,kind,name,status,metadata_json,created_at,updated_at) VALUES(?,?,?,'active',?,?,?)",p.id??act.object_id,p.kind??"unknown",p.name??act.object_id,toJson(p.metadata??{}),t,t); break;
    case "artifact.recognized": db.run("INSERT OR IGNORE INTO artifacts(id,entity_id,kind,name,description,metadata_json,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?)",p.id??act.object_id,p.entityId??null,p.kind??"unknown",p.name??act.object_id,p.description??null,toJson(p.metadata??{}),t,t); break;
    case "artifact.version.recognized": db.run("INSERT OR IGNORE INTO artifact_versions(id,artifact_id,version,content_digest,source_uri,revision,media_type,metadata_json,created_at) VALUES(?,?,?,?,?,?,?,?,?)",p.id??act.object_id,p.artifactId,p.version,p.contentDigest??null,p.sourceUri??null,p.revision??null,p.mediaType??null,toJson(p.metadata??{}),t); break;
    case "contract.recognized": db.run("INSERT OR IGNORE INTO contracts(id,kind,name,status,document_digest,schema_uri,metadata_json,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?)",p.id??act.object_id,p.kind??"unknown",p.name??act.object_id,p.status??"draft",p.documentDigest??null,p.schemaUri??null,toJson(p.metadata??{}),t,t); break;
    case "grant.issued": db.run("INSERT OR IGNORE INTO grants(id,subject_entity_id,capability,resource_pattern,effect,status,metadata_json,created_at,expires_at) VALUES(?,?,?,?,?,'active',?,?,?)",p.id??act.object_id,p.subjectEntityId,p.capability,p.resourcePattern??"*",p.effect??"allow",toJson(p.metadata??{}),t,p.expiresAt??null); break;
    case "app_contract.recognized": db.run("INSERT OR IGNORE INTO app_contracts(id,app_entity_id,version,status,contract_json,content_digest,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?)",p.id??act.object_id,p.appEntityId,p.version,p.status??"draft",toJson(p.contract??{}),p.contentDigest??null,t,t); break;
    case "decision.recorded": db.run("INSERT OR IGNORE INTO decision_records(id,owner_entity_id,decision,context,options_json,evidence_json,consequences,reversal_trigger,status,version,created_at) VALUES(?,?,?,?,?,?,?,?,'current',1,?)",p.id??act.object_id,p.ownerEntityId??null,p.decision,p.context,toJson(p.options??[]),toJson(p.evidence??[]),p.consequences??null,p.reversalTrigger??null,t); break;
    case "incident.opened": db.run("INSERT OR IGNORE INTO incidents(id,kind,title,impact,actions_json,owner_entity_id,status,created_at) VALUES(?,?,?,?,?,?,'open',?)",p.id??act.object_id,p.kind,p.title,p.impact,toJson(p.actions??[]),p.ownerEntityId??null,t); break;
    case "study.created": db.run("INSERT OR IGNORE INTO studies(id,title,decision_question,current_belief,current_confidence,study_class,unit_under_test_json,hypothesis,resource_regime_json,primary_outcomes_json,verification_plan,analysis_method,status,owner_entity_id,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,'planned',?,?,?)",p.id??act.object_id,p.title,p.decisionQuestion,p.currentBelief??null,p.currentConfidence??null,p.studyClass,toJson(p.unitUnderTest??{}),p.hypothesis??null,toJson(p.resourceRegime??{}),toJson(p.primaryOutcomes??[]),p.verificationPlan??null,p.analysisMethod??null,p.ownerEntityId??null,t,t); break;
    case "study.status.changed": db.run("UPDATE studies SET status=?,updated_at=?,completed_at=? WHERE id=?",p.status,t,p.status==="complete"?t:null,act.object_id); break;
    case "study.comparator.added": db.run("INSERT OR IGNORE INTO study_comparators(id,study_id,label,configuration_json,fairness_regime,created_at) VALUES(?,?,?,?,?,?)",p.id??act.object_id,p.studyId,p.label,toJson(p.configuration??{}),p.fairnessRegime??null,t); break;
    case "run.started": db.run("INSERT OR IGNORE INTO runs(id,study_id,comparator_id,result_state,environment_json,resource_usage_json,route_json,started_at) VALUES(?,?,?,'incomplete',?,?,?,?)",p.id??act.object_id,p.studyId,p.comparatorId??null,toJson(p.environment??{}),toJson(p.resourceUsage??{}),toJson(p.route??{}),p.startedAt??t); break;
    case "run.completed": db.run("UPDATE runs SET result_state=?,notes=?,completed_at=? WHERE id=?",p.resultState,p.notes??null,p.completedAt??t,act.object_id); break;
    case "observation.recorded": db.run("INSERT OR IGNORE INTO observations(id,run_id,kind,value_json,observed_at,source_digest,metadata_json) VALUES(?,?,?,?,?,?,?)",p.id??act.object_id,p.runId,p.kind,toJson(p.value),p.observedAt??t,p.sourceDigest??null,toJson(p.metadata??{})); break;
    case "measurement.recorded": db.run("INSERT OR IGNORE INTO measurements(id,run_id,observation_id,metric,value_number,value_text,unit,is_primary,verifier,measured_at,metadata_json) VALUES(?,?,?,?,?,?,?,?,?,?,?)",p.id??act.object_id,p.runId,p.observationId??null,p.metric,p.valueNumber??null,p.valueText??null,p.unit??null,p.isPrimary?1:0,p.verifier??null,t,toJson(p.metadata??{})); break;
    case "finding.recorded": db.run("INSERT OR IGNORE INTO findings(id,study_id,statement,analysis_json,created_at) VALUES(?,?,?,?,?)",p.id??act.object_id,p.studyId,p.statement,toJson(p.analysis??{}),t); break;
    case "claim.recorded": if(p.supersedesId)db.run("UPDATE claims SET status='superseded',updated_at=? WHERE id=?",t,p.supersedesId); db.run("INSERT OR IGNORE INTO claims(id,study_id,statement,scope,status,freshness_state,review_trigger,observed_through,created_at,updated_at,supersedes_id) VALUES(?,?,?,?,?,'current',?,?,?,?,?)",p.id??act.object_id,p.studyId??null,p.statement,p.scope,p.status??"provisional",p.reviewTrigger??null,p.observedThrough??null,t,t,p.supersedesId??null); break;
    case "claim.evidence.linked": db.run("INSERT OR IGNORE INTO claim_evidence(id,claim_id,evidence_kind,evidence_id,stance,notes,created_at) VALUES(?,?,?,?,?,?,?)",p.id??act.object_id,p.claimId,p.evidenceKind,p.evidenceId,p.stance,p.notes??null,t); break;
    case "claim.confidence.assessed": db.run("INSERT OR IGNORE INTO confidence_assessments(id,claim_id,level,rationale,dimensions_json,assessed_by,created_at) VALUES(?,?,?,?,?,?,?)",p.id??act.object_id,p.claimId,p.level,p.rationale,toJson(p.dimensions??{}),p.assessedBy??act.actor_id,t); break;
    case "conclusion.recorded": db.run("INSERT OR IGNORE INTO conclusions(id,study_id,interpretation,created_at) VALUES(?,?,?,?)",p.id??act.object_id,p.studyId,p.interpretation,t); break;
    case "recommendation.recorded": if(p.supersedesId)db.run("UPDATE recommendations SET status='superseded' WHERE id=?",p.supersedesId); db.run("INSERT OR IGNORE INTO recommendations(id,study_id,claim_id,action,constraints_json,status,retest_trigger,created_at,supersedes_id) VALUES(?,?,?,?,?,'current',?,?,?)",p.id??act.object_id,p.studyId??null,p.claimId??null,p.action,toJson(p.constraints??{}),p.retestTrigger??null,t,p.supersedesId??null); break;
    case "content.preserved": db.run("INSERT OR IGNORE INTO content_objects(digest,algorithm,size_bytes,media_type,object_kind,manifest_json,created_by,created_at,verified_at) VALUES(?,'sha256',?,?,?,?,?,?,?)",p.digest??act.object_id,p.sizeBytes??0,p.mediaType??"application/octet-stream",p.objectKind??"blob",p.manifest?toJson(p.manifest):null,act.actor_id,t,t); break;
    case "execution_route.created": db.run("INSERT OR IGNORE INTO execution_routes(id,name,configuration_json,status,created_at,updated_at) VALUES(?,?,?,'active',?,?)",p.id??act.object_id,p.name,toJson(p.configuration??{}),t,t); break;
    case "executable_contract.created": db.run("INSERT OR IGNORE INTO executable_contracts(id,name,generation,status,temporal_predicate_json,observational_predicate_json,policy_json,effect_json,verification_json,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?)",p.id??act.object_id,p.name,p.generation??1,p.status??"draft",toJson(p.temporalPredicate??{}),toJson(p.observationalPredicate??{}),toJson(p.policy??{}),toJson(p.effect??{}),toJson(p.verification??{}),t,t); break;
    case "executable_contract.status.changed": db.run("UPDATE executable_contracts SET status=?,updated_at=? WHERE id=?",p.status,t,act.object_id); break;
    case "execution.triggered": db.run("INSERT OR IGNORE INTO executions(id,contract_id,contract_generation,trigger_json,state,idempotency_key,created_at) VALUES(?,?,?,?,'ready',?,?)",p.id??act.object_id,p.contractId,p.generation??1,toJson(p.trigger??{}),p.idempotencyKey,t); break;
    case "execution.verified": case "execution.uncertain": db.run("UPDATE executions SET state=?,completed_at=? WHERE id=?",act.kind==="execution.verified"?"done":"uncertain",t,act.object_id); if(p.receiptId)db.run("INSERT OR IGNORE INTO execution_receipts(id,execution_id,receipt_kind,payload_json,verified,created_at) VALUES(?,?,?, ?,?,?)",p.receiptId,act.object_id,p.result?.type??"replay",toJson(p.result??{}),p.verified?1:0,t); break;
    case "execution.lease.expired": if(p.state==="ready")db.run("UPDATE executions SET state='ready',claimed_by=NULL,claimed_at=NULL WHERE id=?",act.object_id); else db.run("UPDATE executions SET state='uncertain',completed_at=?,error_text=? WHERE id=?",t,"Lease expired while executing; effect certainty unknown",act.object_id); break;
    case "execution.failed": db.run("UPDATE executions SET state='failed',error_text=?,completed_at=? WHERE id=?",p.error??"replayed failure",t,act.object_id); break;
    case "product_candidate.recorded": db.run("INSERT OR IGNORE INTO product_candidates(id,name,problem,product_class,recurring_decision,differentiated_value,maintenance_case,demand_evidence,external_alternatives,status,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,'candidate',?,?)",p.id??act.object_id,p.name,p.problem,p.productClass,p.recurringDecision??null,p.differentiatedValue??null,p.maintenanceCase??null,p.demandEvidence??null,p.externalAlternatives??null,t,t); break;
    case "product.promoted": db.run("INSERT OR IGNORE INTO products(id,candidate_id,name,product_class,status,value_proposition,maintenance_trigger,visibility,created_at,updated_at) VALUES(?,?,?,?,'active',?,?,?,?,?)",p.id??act.object_id,p.candidateId??null,p.name,p.productClass,p.valueProposition,p.maintenanceTrigger??null,p.visibility??"internal",t,t); db.run("UPDATE product_candidates SET status='promoted',updated_at=? WHERE id=?",t,p.candidateId); break;
    case "publication.recorded": db.run("INSERT OR IGNORE INTO publication_records(id,product_id,claim_id,title,visibility,content_digest,published_at,supersedes_id,created_at) VALUES(?,?,?,?,?,?,?,?,?)",p.id??act.object_id,p.productId??null,p.claimId??null,p.title,p.visibility??"internal",p.contentDigest??null,p.publishedAt??t,p.supersedesId??null,t); if(p.supersedesId)db.run("UPDATE publication_records SET corrected_at=? WHERE id=?",t,p.supersedesId); break;
    case "benchmark.created": db.run("INSERT OR IGNORE INTO benchmark_instruments(id,name,version,status,methodology_digest,comparability_boundary,contamination_strategy,notes,created_at) VALUES(?,?,?,'active',?,?,?,?,?)",p.id??act.object_id,p.name,p.version,p.methodologyDigest??null,p.comparabilityBoundary??null,p.contaminationStrategy??null,p.notes??null,t); break;
    case "benchmark.task.added": db.run("INSERT OR IGNORE INTO benchmark_tasks(id,benchmark_id,task_key,instructions_digest,success_criteria_json,grader_json,sequestered,created_at) VALUES(?,?,?,?,?,?,?,?)",p.id??act.object_id,p.benchmarkId,p.taskKey,p.instructionsDigest??null,toJson(p.successCriteria??{}),toJson(p.grader??{}),p.sequestered?1:0,t); break;
    case "test_bench.created": db.run("INSERT OR IGNORE INTO test_benches(id,study_id,benchmark_id,name,configuration_json,resource_regime_json,verification_json,created_at) VALUES(?,?,?,?,?,?,?,?)",p.id??act.object_id,p.studyId,p.benchmarkId??null,p.name,toJson(p.configuration??{}),toJson(p.resourceRegime??{}),toJson(p.verification??{}),t); break;
    case "observational_evidence.recorded": case "temporal_evidence.recorded": db.run("INSERT OR IGNORE INTO evidence_signals(id,domain,kind,subject,value_json,observed_at,source_digest,metadata_json) VALUES(?,?,?,?,?,?,?,?)",p.id??act.object_id,p.domain,p.kind,p.subject,toJson(p.value),p.observedAt??t,p.sourceDigest??null,toJson(p.metadata??{})); break;
    default: break;
  }
  db.run("INSERT OR IGNORE INTO recorded_acts(id,actor_id,kind,object_type,object_id,payload_json,evidence_digest,created_at) VALUES(?,?,?,?,?,?,?,?)",act.id,act.actor_id,act.kind,act.object_type,act.object_id,toJson(p),act.evidence_digest??null,t);
}

export function replayAll(db:Database,acts:ReplayAct[]):void{for(const act of acts.sort((a:any,b:any)=>(a.seq??0)-(b.seq??0)))replayAct(db,act)}
